name: Keystone CMS Docker Build Cache Save Artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clone portal cms # checkout main
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: USSF-ORBIT/ussf-portal-cms
          ref: main
          path: ./ussf-portal-cms
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        id: buildx
        with:
          install: true

      - name: Build Keystone to e2e Stage
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: ./ussf-portal-cms
          tags: keystone-cms:e2e
          cache-to: type=local,mode=max,dest=/tmp/keystone-cms,tag=e2e
          target: e2e

      - name: Get docker image digest from manifest
        id: manifest
        run: |
          digest=$(cat /tmp/keystone-cms/index.json | jq -r '.manifests[0].digest')
          echo "docker_tag=${digest##sha256:}" >> $GITHUB_OUTPUT

      - name: Save docker cache to GHA cache using image digest as key
        uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: /tmp/keystone-cms
          key: ${{ runner.os }}-docker-keystone-cms-${{ steps.manifest.outputs.docker_tag }}
