name: Personnel API Docker Build Cache Save Artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Personnel API # checkout main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          repository: USSF-ORBIT/ussf-personnel-api 
          ref: main
          path: ./ussf-personnel-api 
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        id: buildx
        with:
          install: true

      - name: Build Personnel API to builder Stage
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          context: ./ussf-personnel-api 
          tags: personnel-api:builder
          cache-to: type=local,mode=max,dest=/tmp/personnel-api,tag=builder
          target: builder

      - name: Get docker image digest from manifest
        id: manifest
        run: |
          digest=$(cat /tmp/personnel-api/index.json | jq -r '.manifests[0].digest')
          echo "docker_tag=${digest##sha256:}" >> $GITHUB_OUTPUT

      - name: Save docker cache to GHA cache using image digest as key
        uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: /tmp/personnel-api 
          key: ${{ runner.os }}-docker-personnel-api-${{ steps.manifest.outputs.docker_tag }}
