on:
  # make the workflow reusable
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      release-type:
        required: true
        type: string

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3
        with:
          release-type: ${{ inputs.release-type }}
          package-name: ${{ inputs.package-name }}
          release-labels: 'type: release'
          include-v-in-tag: false
          token: ${{ secrets.RELEASE_PLEASE_TOKEN}}
          changelog-types: >
            [
              { "type": "build", "hidden": true },
              { "type": "chore", "hidden": true },
              { "type": "ci", "hidden": true },
              { "type": "dev", "hidden": true },
              { "type": "feat", "section": "Features" },
              { "type": "fix", "section": "Bug Fixes" },
              { "type": "perf", "section": "Performance Improvements" },
              { "type": "refactor", "hidden": true },
              { "type": "revert", "section": "Reverted Changes" },
              { "type": "style", "hidden": true },
              { "type": "test", "hidden": true },
              { "type": "docs", "section": "Documentation" },
              { "type": "security", "section": "Security Improvements" }
            ]
